app/spotify/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import InputRequired, Length


class CourseForm(FlaskForm):
    search_term = StringField('Search: ', validators=[InputRequired(),
                                             Length(min=1, max=100)])

app/spotify/__init__.py
from flask import Blueprint
from app.spotify.cache import cache

bp = Blueprint('spotify', __name__)

from app.spotify import routes

app/spotify/routes.py
from app.spotify import bp, cache
from flask import render_template, request, redirect, url_for, render_template_string, flash
from flask_login import login_required, current_user
from sqlalchemy import desc

from app.models.charts import recently_played, daily_artists ,daily_tracks
from app.models.catalogs import track_catalog, artist_catalog
from app.models.playlists import Playlists
from app.models.accounts import artist_comments

from app import db

from app.dash_plotlys.plotly_figures import chart_scatter_plotly

from app.spotify.forms import CourseForm
from app.forms import CommentForm, SearchForm

import app.spotify.daily_funcs as daily_funcs
import app.spotify.art_cat_funcs as ac_funcs
from app.spotify.plotly_figs import top_5_artists_fig, top_5_tracks_fig


from datetime import datetime

#YOU CANT HAVE ANYTHING OUTSIDE OF DECORATED ROUTES! Do it somewhere else and import it.
#latest_daily_date = daily_tracks.query.order_by(daily_tracks.id.desc()).first().date
#latest_date_obj = datetime.strptime(latest_daily_date, "%Y-%m-%d").date()


###############################
##Playlists
#@bp.route('/spotify/playlist/<string:playlist_id>', methods=('GET','POST'))
@bp.route('/spotify/playlist', methods=('GET','POST'))
def playlist_homepage():
    '''
    Temp install!
    '''
    #fig = top_5_artists_fig()
    #html = fig.to_html()

    return render_template('spotify/playlist/playlist_timeline.html')

@bp.route('/spotify/playlist/<string:playlist_id>', methods=('GET','POST'))
def playlist_timeline(playlist_id):
    '''
    Temp install!
    '''
    playlist_records = Playlists.filtered_enriched_playlist(playlist_id)
    
    context = {
        'tracks':playlist_records,
    }

    return render_template('spotify/playlist/playlist_timeline.html', **context)


##############################
@bp.route('/spotify/top_five_artists')
@login_required
def top_five_artist_plot():
    '''
    Temp install!
    '''
    fig = top_5_artists_fig()
    html = fig.to_html()

    return render_template_string(html)

@bp.route('/spotify/top_five_tracks')
@login_required
def top_five_tracks_plot():
    '''
    No sidebar!
    '''
    fig = top_5_tracks_fig()
    html = fig.to_html()

    return render_template_string(html)


#############################################
@bp.route('/spotify')
@bp.route('/spotify/')
def spotify_landing_page():
    '''
    I guess this should look flashy and have a menu that offers something the sidebar of the regular Spotify
    views or the art_cat_base do not offer. Or just a very simple menu, but flashier?
    '''
    latest_5 = ac_funcs.latest_art_cats()
    top_5_arts = daily_funcs.top_ever_daily_artists(5)
    top_5_tracks = daily_funcs.top_ever_daily_tracks(5)
    daily_rp_avg = recently_played.rp_average_per_day()

    context = {
        'latest_artists':latest_5,
        'top_5_arts' : top_5_arts,
        'top_5_tracks' : top_5_tracks,
        'daily_rp_avg' : daily_rp_avg,
        
    }
    return render_template('spotify/spotify_homepage.html', **context)


###########################################
# art_cat routes

@bp.route('/spotify/art_cat/', methods=('GET','POST'))
@bp.route('/spotify/art_cat', methods=('GET','POST'))
def art_cat_landing_page():
    form = CourseForm()
    #if form.validate_on_submit():
    if request.method == 'POST':
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))

    thruples = ac_funcs.genre_landing_thruples()

    context = {
        'thruples' : thruples,
        'form':form,
    }

    return render_template('spotify/art_cat/art_cat_landing.html', **context)


# Adding Comments to artist
@bp.route('/spotify/art_cat/artist/<string:art_id>', methods=('GET','POST'))
def art_cat_profile(art_id):
    form = SearchForm()
    comment_form = CommentForm()

    if (form.validate_on_submit()):
        print('search bar was used')
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))
    
    
    if comment_form.validate_on_submit():
        print('comment was made')
        if not current_user.is_authenticated:
            flash('You must be logged in to add a comment.', 'warning')
            return redirect(url_for('user_accounts.login'))  # Redirect to login page if not logged in
        
        art_comment = artist_comments(
            content=comment_form.content.data,
            artist_catalog_id=art_id,
            user_id=current_user.id,
            comment_date=datetime.utcnow())
        
        db.session.add(art_comment)
        db.session.commit()
        return redirect(url_for('spotify.art_cat_profile', art_id=art_id))

    profile_context = ac_funcs.art_cat_profile(art_id)
    profile_context['form'] = form
    profile_context['comment_form'] = comment_form

    print('profile got GET')
    return render_template('spotify/art_cat/art_cat_profile.html', **profile_context)

#######################
#Three index routes. They need pagination.
#How?

@bp.route('/spotify/art_cat/<string:letter>', methods=('GET','POST'))
def index_by_letter(letter):
    page = request.args.get('page', 1, type=int)
    form = CourseForm()
    #if form.validate_on_submit():
    if request.method == 'POST':
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))
    
    art_cat_index, total_count = ac_funcs.all_art_cats_starting_with(
        letter,
        page,
        )
    
    context = {
        'art_cat_index' : art_cat_index.items,
        'letter' : letter,
        'form':form,
        'artist_count': total_count,
        'prev_page':art_cat_index.prev_num,
        'next_page':art_cat_index.next_num,
        'first_page':1,
        'last_page':art_cat_index.pages,
    }

    return render_template('spotify/art_cat/art_cat_index.html', **context)



@bp.route('/spotify/art_cat/genre/<string:master_genre>', methods=('GET','POST'))
@bp.route('/spotify/art_cat/genre', defaults={'master_genre': None}, methods=('GET','POST'))
def index_by_genre(master_genre):
    page = request.args.get('page', 1, type=int)
    form = CourseForm()
    #if form.validate_on_submit():
    if request.method == 'POST':
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))
    
    sort = request.args.get('sort','default')

    if (master_genre in ac_funcs.genres)|(master_genre is None) :
        art_cat_index, ac_count = ac_funcs.all_art_cats_in_master_genre(
            master_genre, 
            page,
            sort
            )    
    else:
        art_cat_index, ac_count = ac_funcs.art_cats_with_this_genre(
            master_genre, 
            page,
            sort,
            )


    context = {
        'genre': master_genre,
        'artist_count': ac_count,
        'art_cat_index': art_cat_index.items,
        'form':form,
        'prev_page':art_cat_index.prev_num,
        'next_page':art_cat_index.next_num,
        'first_page':1,
        'last_page':art_cat_index.pages,
        'sort':sort,
    }

    return render_template('spotify/art_cat/art_cat_index.html', **context)

@bp.route('/spotify/search/<string:search_term>', methods=('GET','POST'))
def index_by_search(search_term):
    form = CourseForm()
    if request.method == 'POST':
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))

    like_arts = ac_funcs.art_cat_name_search(search_term)

    context = {
        'like_arts':like_arts,
        'form':form,
    }

    return render_template('spotify/art_cat/art_cat_search.html', **context)

###########################################
###########################################
#track_cat routes

@bp.route('/spotify/track_cat/', methods=('GET','POST'))
@bp.route('/spotify/track_cat', methods=('GET','POST'))
def track_cat_landing_page():

    thruples = track_catalog.track_cat_landing_thruples()

    context = {
        'thruples' : thruples,
    }

    return render_template('spotify/track_cat/track_cat_landing.html', **context)

@bp.route('/spotify/track_cat/<string:letter>')
def index_tracks_by_letter(letter):
    
    track_index = track_catalog.all_tracks_starting_with(letter)
    
    context = {
        'track_index' : track_index,
        'letter' : letter,
    }

    return render_template('spotify/track_cat/track_index.html', **context)


###############
###########################################
#rp routes
@bp.route('/spotify/yesterday')
@bp.route('/spotify/yesterday/')
@cache.cached(timeout=3600)
def yesterday():
    '''
    Route to the recent template.
    '''
    #three_ago = recently_played.query.all()[-3:]
    yesterday_records = recently_played.past_24_hrs_rps()
    song_count_yesterday = len(yesterday_records)
    distinct_arts = len(list(set([i.art_name for i in yesterday_records])))
    known, unknown = recently_played.scan_for_art_cat_awareness(yesterday_records)
    known_cats = list(map(
        artist_catalog.name_to_art_cat,
        known,
    ))
    sorted_known_cats = sorted(known_cats, key=lambda x: (x.master_genre.lower(), x.art_name.lower()))
    context = {
        #'last_three' : three_ago,
        'yesterday_song_count' : song_count_yesterday,
        'distinct_arts' : distinct_arts,
        'known':known,
        'unknown':sorted(unknown, key=lambda x: (x.lower(), x)),
        'known_cats':sorted_known_cats,
    }
    return render_template('spotify/recently_played.html', **context)

@bp.route('/spotify/right_now')
@bp.route('/spotify/right_now/')
#@cache.cached(timeout=3600)
def right_now():
    '''
    Route to the recent template.
    '''
    page = request.args.get('page', 1, type=int)
    per_page = 5
    pagination = recently_played.query.order_by(desc(recently_played.id)).paginate(page=page, per_page=per_page, error_out=False)
    five_ago = pagination.items
    
    cat_scanned = list(map(
        recently_played.cat_scan_rp_object,
        five_ago
    ))

    context = {
        'last_five': cat_scanned,

app/templates/spotify/track_cat/track_cat_landing.html
{% extends 'base.html' %}

{% block content %}
<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/spotify.css') }}">

<style>
    body {
    background-color: #0f1f19;
    color: wheat;
  }

    .container {
        max-width: 900px; /* Set the maximum width of the container */
    }

    .card {
        width: 100%;
        height: 100%;
        border: 2px solid;
        transition: background-color 0.3s ease, box-shadow 0.3s ease; /* Add box-shadow to the transition */
    }

    .card:hover {
        box-shadow: inset 0 0 80px rgba(0, 0, 0, 0.5); /* Add inner shadow on hover */
    }

    .card-img-top {
        max-height: 170px; /* Adjust the maximum height of the image */
        object-fit: cover;
    }
</style>

<title>Fred's Spotify Record Collection</title>

{% include 'spotify/spotify_header.html' %}

<div class="container mt-5 text-center">
    <h3 style="color: wheat;">Fred's Spotify Record Collection</h3>
    <div class="row">

        {% for cell in thruples %}
            <div class="col-md-2 mb-4">
                <div class="card" style="background-color: darkcyan;">
                    <a href="{{ url_for('spotify.index_tracks_by_letter', letter=cell.0) }}">
                        <img src="https://i.scdn.co/image/{{ cell.2 }}" class="card-img-top" alt="Image">
                    </a>
                    <div class="card-body">
                        <h5 class="circle">{{ cell.0 }}</h5>
                        <p class="card-text">{{ cell.1 }} tracks</p>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
</div>

{% endblock %}

app/templates/spotify/track_cat/track_header.html
{% set alpha = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'] %}
<style>
.alpha-list {
  background-color: antiquewhite;
  border-radius: 62%;
  border-bottom: 2px solid brown;
  list-style-type: none;
  padding: 0;
}

.alpha-pill {
  background-color: rgb(71, 146, 71);
  color: lightgray;
  border-radius: 20px;
  display: inline-block;
  padding: 5px 10px;
  margin: 2px;
  text-decoration: none;
}

.alpha-pill:hover {
  box-shadow: 0 0 19px rgba(0, 0, 0, 0.5); /* Add drop shadow on hover */
}
</style>  
    
{% include 'spotify/spotify_header.html' %}

<div class="container-fluid text-center">
    <div class="myDiv">
        <!-- Navigation Links -->
        <nav>

        {% for letter in alpha %}
        <a href="{{ url_for('spotify.index_tracks_by_letter', letter=letter) }}" class="alpha-pill">{{ letter }}</a>
        {% endfor %}
        </nav>

    </div>
</div>
    

app/templates/spotify/track_cat/track_index.html
{% include 'base.html' %}

{% block content %}
<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/spotify.css') }}">

{% include 'spotify/track_cat/track_header.html' %}

<title>{{ letter }} Tracks</title>

<style>
    .container {
  max-width: 76%;
}
</style>

<div class="container text-center">

    {% if track_index is not defined or track_index|length == 0 %}
    <p>The variable is empty or undefined.</p>
    {% else %}
        {% if letter is defined %}
        <p>{{ track_index|length }} tracks when indexed by {{ letter }}</p>
        {% endif %}
    {% endif %}

    <div class="row">
        {% for track in track_index %}

        {% include 'spotify/track_cat/track_record_card.html' %}
        
        {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/spotify/track_cat/track_record_card.html
<div class="col-md-3" style="padding-top: 33px;">
    <div class="card" style="width: 18rem; background-color: darkcyan;">
        
        {% if track.img_url == '' %}
        <img src="{{ url_for('static', filename='/img/fallback.jpeg') }}" class="card-img-top my-image" alt="{{ track.song_name }}">
        {% else %}
        <img src="https://i.scdn.co/image/{{ track.img_url }}" title="Que culazo!" class="card-img-top my-image">
        {% endif %}
    
        <a href="https://open.spotify.com/track/{{ track.song_id }}" class="list-group-item list-group-item-action custom-list-item">
            <b>{{ track.song_name }}</b>
            <p>by <b>{{ track.art_name }}</p></b>
        </a>
        
        {% if track.song_name != track.album_name %}
            <small>album: </small><p style="display: inline;">{{ track.album_name }}</p>
        {% endif %}


        <p>{{ track.duration // 1000 }} seconds </p>
    </div>
</div>

app/templates/spotify/track_cat/track_sidebar.html
{% set alpha = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'] %}

<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/sidebar.css') }}">

<style>
</style>

<aside>
    <a href="{{ url_for('spotify.spotify_landing_page')  }}">
      <i class="fa fa-home" aria-hidden="true"></i>
      Spotify Home
    </a>

    <a href="{{ url_for('spotify.art_cat_landing_page')  }}">
        <i class="fa fa-list" aria-hidden="true"></i>
        Artist Catalog
    </a>

    <a href="{{ url_for('spotify.track_cat_landing_page')  }}">
        <i class="fa fa-sign" aria-hidden="true"></i>
        Track Catalog
    </a>

    {% for letter in alpha %}
        <a href="{{ url_for('spotify.index_tracks_by_letter', letter=letter) }}">{{ letter }}</a>
    {% endfor %}
</aside>