app/spotify/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import InputRequired, Length


class CourseForm(FlaskForm):
    search_term = StringField('Search: ', validators=[InputRequired(),
                                             Length(min=1, max=100)])

app/spotify/__init__.py
from flask import Blueprint
from app.spotify.cache import cache

bp = Blueprint('spotify', __name__)

from app.spotify import routes

app/spotify/routes.py
from app.spotify import bp, cache
from flask import render_template, request, redirect, url_for, render_template_string, flash
from flask_login import login_required, current_user
from sqlalchemy import desc

from app.models.charts import recently_played, daily_artists ,daily_tracks
from app.models.catalogs import track_catalog, artist_catalog
from app.models.playlists import Playlists
from app.models.accounts import artist_comments

from app import db

from app.dash_plotlys.plotly_figures import chart_scatter_plotly

from app.spotify.forms import CourseForm
from app.forms import CommentForm, SearchForm

import app.spotify.daily_funcs as daily_funcs
import app.spotify.art_cat_funcs as ac_funcs
from app.spotify.plotly_figs import top_5_artists_fig, top_5_tracks_fig


from datetime import datetime

#YOU CANT HAVE ANYTHING OUTSIDE OF DECORATED ROUTES! Do it somewhere else and import it.
#latest_daily_date = daily_tracks.query.order_by(daily_tracks.id.desc()).first().date
#latest_date_obj = datetime.strptime(latest_daily_date, "%Y-%m-%d").date()


###############################
##Playlists
#@bp.route('/spotify/playlist/<string:playlist_id>', methods=('GET','POST'))
@bp.route('/spotify/playlist', methods=('GET','POST'))
def playlist_homepage():
    '''
    Temp install!
    '''
    #fig = top_5_artists_fig()
    #html = fig.to_html()

    return render_template('spotify/playlist/playlist_timeline.html')

@bp.route('/spotify/playlist/<string:playlist_id>', methods=('GET','POST'))
def playlist_timeline(playlist_id):
    '''
    Temp install!
    '''
    playlist_records = Playlists.filtered_enriched_playlist(playlist_id)
    
    context = {
        'tracks':playlist_records,
    }

    return render_template('spotify/playlist/playlist_timeline.html', **context)


##############################
@bp.route('/spotify/top_five_artists')
@login_required
def top_five_artist_plot():
    '''
    Temp install!
    '''
    fig = top_5_artists_fig()
    html = fig.to_html()

    return render_template_string(html)

@bp.route('/spotify/top_five_tracks')
@login_required
def top_five_tracks_plot():
    '''
    No sidebar!
    '''
    fig = top_5_tracks_fig()
    html = fig.to_html()

    return render_template_string(html)


#############################################
@bp.route('/spotify')
@bp.route('/spotify/')
def spotify_landing_page():
    '''
    I guess this should look flashy and have a menu that offers something the sidebar of the regular Spotify
    views or the art_cat_base do not offer. Or just a very simple menu, but flashier?
    '''
    latest_5 = ac_funcs.latest_art_cats()
    top_5_arts = daily_funcs.top_ever_daily_artists(5)
    top_5_tracks = daily_funcs.top_ever_daily_tracks(5)
    daily_rp_avg = recently_played.rp_average_per_day()

    context = {
        'latest_artists':latest_5,
        'top_5_arts' : top_5_arts,
        'top_5_tracks' : top_5_tracks,
        'daily_rp_avg' : daily_rp_avg,
        
    }
    return render_template('spotify/spotify_homepage.html', **context)


###########################################
# art_cat routes

@bp.route('/spotify/art_cat/', methods=('GET','POST'))
@bp.route('/spotify/art_cat', methods=('GET','POST'))
def art_cat_landing_page():
    form = CourseForm()
    #if form.validate_on_submit():
    if request.method == 'POST':
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))

    thruples = ac_funcs.genre_landing_thruples()

    context = {
        'thruples' : thruples,
        'form':form,
    }

    return render_template('spotify/art_cat/art_cat_landing.html', **context)


# Adding Comments to artist
@bp.route('/spotify/art_cat/artist/<string:art_id>', methods=('GET','POST'))
def art_cat_profile(art_id):
    form = SearchForm()
    comment_form = CommentForm()

    if (form.validate_on_submit()):
        print('search bar was used')
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))
    
    
    if comment_form.validate_on_submit():
        print('comment was made')
        if not current_user.is_authenticated:
            flash('You must be logged in to add a comment.', 'warning')
            return redirect(url_for('user_accounts.login'))  # Redirect to login page if not logged in
        
        art_comment = artist_comments(
            content=comment_form.content.data,
            artist_catalog_id=art_id,
            user_id=current_user.id,
            comment_date=datetime.utcnow())
        
        db.session.add(art_comment)
        db.session.commit()
        return redirect(url_for('spotify.art_cat_profile', art_id=art_id))

    profile_context = ac_funcs.art_cat_profile(art_id)
    profile_context['form'] = form
    profile_context['comment_form'] = comment_form

    print('profile got GET')
    return render_template('spotify/art_cat/art_cat_profile.html', **profile_context)

#######################
#Three index routes. They need pagination.
#How?

@bp.route('/spotify/art_cat/<string:letter>', methods=('GET','POST'))
def index_by_letter(letter):
    page = request.args.get('page', 1, type=int)
    form = CourseForm()
    #if form.validate_on_submit():
    if request.method == 'POST':
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))
    
    art_cat_index, total_count = ac_funcs.all_art_cats_starting_with(
        letter,
        page,
        )
    
    context = {
        'art_cat_index' : art_cat_index.items,
        'letter' : letter,
        'form':form,
        'artist_count': total_count,
        'prev_page':art_cat_index.prev_num,
        'next_page':art_cat_index.next_num,
        'first_page':1,
        'last_page':art_cat_index.pages,
    }

    return render_template('spotify/art_cat/art_cat_index.html', **context)



@bp.route('/spotify/art_cat/genre/<string:master_genre>', methods=('GET','POST'))
@bp.route('/spotify/art_cat/genre', defaults={'master_genre': None}, methods=('GET','POST'))
def index_by_genre(master_genre):
    page = request.args.get('page', 1, type=int)
    form = CourseForm()
    #if form.validate_on_submit():
    if request.method == 'POST':
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))
    
    sort = request.args.get('sort','default')

    if (master_genre in ac_funcs.genres)|(master_genre is None) :
        art_cat_index, ac_count = ac_funcs.all_art_cats_in_master_genre(
            master_genre, 
            page,
            sort
            )    
    else:
        art_cat_index, ac_count = ac_funcs.art_cats_with_this_genre(
            master_genre, 
            page,
            sort,
            )


    context = {
        'genre': master_genre,
        'artist_count': ac_count,
        'art_cat_index': art_cat_index.items,
        'form':form,
        'prev_page':art_cat_index.prev_num,
        'next_page':art_cat_index.next_num,
        'first_page':1,
        'last_page':art_cat_index.pages,
        'sort':sort,
    }

    return render_template('spotify/art_cat/art_cat_index.html', **context)

@bp.route('/spotify/search/<string:search_term>', methods=('GET','POST'))
def index_by_search(search_term):
    form = CourseForm()
    if request.method == 'POST':
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))

    like_arts = ac_funcs.art_cat_name_search(search_term)

    context = {
        'like_arts':like_arts,
        'form':form,
    }

    return render_template('spotify/art_cat/art_cat_search.html', **context)

###########################################
###########################################
#track_cat routes

@bp.route('/spotify/track_cat/', methods=('GET','POST'))
@bp.route('/spotify/track_cat', methods=('GET','POST'))
def track_cat_landing_page():

    thruples = track_catalog.track_cat_landing_thruples()

    context = {
        'thruples' : thruples,
    }

    return render_template('spotify/track_cat/track_cat_landing.html', **context)

@bp.route('/spotify/track_cat/<string:letter>')
def index_tracks_by_letter(letter):
    
    track_index = track_catalog.all_tracks_starting_with(letter)
    
    context = {
        'track_index' : track_index,
        'letter' : letter,
    }

    return render_template('spotify/track_cat/track_index.html', **context)


###############
###########################################
#rp routes
@bp.route('/spotify/yesterday')
@bp.route('/spotify/yesterday/')
@cache.cached(timeout=3600)
def yesterday():
    '''
    Route to the recent template.
    '''
    #three_ago = recently_played.query.all()[-3:]
    yesterday_records = recently_played.past_24_hrs_rps()
    song_count_yesterday = len(yesterday_records)
    distinct_arts = len(list(set([i.art_name for i in yesterday_records])))
    known, unknown = recently_played.scan_for_art_cat_awareness(yesterday_records)
    known_cats = list(map(
        artist_catalog.name_to_art_cat,
        known,
    ))
    sorted_known_cats = sorted(known_cats, key=lambda x: (x.master_genre.lower(), x.art_name.lower()))
    context = {
        #'last_three' : three_ago,
        'yesterday_song_count' : song_count_yesterday,
        'distinct_arts' : distinct_arts,
        'known':known,
        'unknown':sorted(unknown, key=lambda x: (x.lower(), x)),
        'known_cats':sorted_known_cats,
    }
    return render_template('spotify/recently_played.html', **context)

@bp.route('/spotify/right_now')
@bp.route('/spotify/right_now/')
#@cache.cached(timeout=3600)
def right_now():
    '''
    Route to the recent template.
    '''
    page = request.args.get('page', 1, type=int)
    per_page = 5
    pagination = recently_played.query.order_by(desc(recently_played.id)).paginate(page=page, per_page=per_page, error_out=False)
    five_ago = pagination.items
    
    cat_scanned = list(map(
        recently_played.cat_scan_rp_object,
        five_ago
    ))

    context = {
        'last_five': cat_scanned,

app/templates/spotify/archive_chart_artists.html
{% include 'base.html' %}

{% block content %}
<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/sidebar.css') }}">
<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/spotify.css') }}">

{% include 'spotify/spotify_header.html' %}

<style>

</style>
<title>
    Daily {{ chart_type }} Archives
</title>


<div class="container" style="max-width: 59%;">

    <div class="row justify-content-center mb-3">
        <div class="col-12 text-center">
            <!-- <a href="http://127.0.0.1:5000/spotify/monthly/{{ date_obj.year }}/{{ date_obj.month }}" class="btn btn-primary">Monthly View</a> -->
            <a href="https://fredlambuth.com/spotify/monthly/{{ date_obj.year }}/{{ date_obj.month }}" class="btn btn-primary">Monthly View</a>
        </div>
    </div>

    
        <h1 class="text-center">Daily {{ chart_type }} Archives</h1>

    
    <div class="row justify-content-center">

        <div class="col-2 text-center">
            <a href="{{ url_for('spotify.arts_prev',year=date_back_1month.year, month=date_back_1month.strftime('%m'), day=date_back_1month.strftime('%d')) }}" class="btn btn-secondary"><<</a>
        </div>

        <div class="col-2 text-center">
            <a href="{{ url_for('spotify.arts_prev',year=date_back_1day.year, month=date_back_1day.strftime('%m'), day=date_back_1day.strftime('%d')) }}" class="btn btn-secondary">&lt;</a>
        </div>

        <div class="col-4 text-center">
            <h4>{{ date_obj.isoformat() }}</h4>
        </div>

        <div class="col-2 text-center">
            <a href="{{ url_for('spotify.arts_prev',year=date_fwd_1day.year, month=date_fwd_1day.strftime('%m'), day=date_fwd_1day.strftime('%d')) }}" class="btn btn-secondary">&gt;</a>
        </div>

        <div class="col-2 text-center">
            <a href="{{ url_for('spotify.arts_prev',year=date_fwd_1month.year, month=date_fwd_1month.strftime('%m'), day=date_fwd_1month.strftime('%d')) }}" class="btn btn-secondary">>></a>
        </div>
    </div>

    <div class="list-group">
        {% for record in records %}
        
        <div class="row align-items-center">
            <div class="col-1">
                <div class="circle">
                    <p>{{ record[0].position }}</p>
                </div>
            </div>
            
            <div class="col-2">
            <img src="https://i.scdn.co/image/{{ record.img_url_sml }}" title="Que culazo!" class="with-border image-container">
            </div>
            
            {% if record.master_genre == 'rock' %}
            <div class="col-4 rock">
        {% elif record.master_genre == 'pop' %}
            <div class="col-4 pop">
        {% elif record.master_genre == 'electronic' %}
            <div class="col-4 electronic">
        {% elif record.master_genre == 'punk' %}
            <div class="col-4 punk">
        {% elif record.master_genre == 'funk' %}
            <div class="col-4 funk">
        {% elif record.master_genre == 'indie' %}
            <div class="col-4 indie">
        {% elif record.master_genre == 'old' %}
            <div class="col-4 old">
        {% elif record.master_genre == 'country' %}
            <div class="col-4 country">
        {% else %}
            <div class="col-4">
        {% endif %}

        {% if chart_type == 'Tracks' %}
            <a href="https://open.spotify.com/track/{{ record[0].song_id }}" class="list-group-item list-group-item-action">
                {{ record[0].song_name }}
                <p>by <b>{{ record[0].art_name }}</p></b>
            </a>
            </div>

            <div class="col-5 white-pill">
                {{ record.genre }} {% if record.genre2 is not none %}, {{ record.genre2 }}{% endif %}
            </div>

        {% elif chart_type == 'Artists' %}
            <a href="https://open.spotify.com/artist/{{ record[0].art_id }}" class="list-group-item list-group-item-action">
                <p><b>{{ record[0].art_name }}</p></b>
            </a>
            </div>

            <div class="col-5 white-pill">
                {{ record.genre }} {% if record.genre2 is not none %}, {{ record.genre2 }}{% endif %}
            </div>

        {% endif %}


        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/spotify/latest_artists.html
{% include 'base.html' %}

{% block content %}
<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/spotify.css') }}">

<title>Today's Top Artists</title>

<style>

</style>

{% include 'spotify/spotify_header.html' %}

<div class="container">
    <div class="row align-items-center">
        <div class="col">
          <a href="{{ url_for('spotify.arts_prev', year=year, month=month_num, day=day ) }}" class="btn btn-primary" style="color: rgb(175, 255, 244);">
            Daily Artists Archives
          </a>
        </div>
    
        <div class="col" style="color: antiquewhite;">
            Top 10 Artists for {{ latest_date }}
        </div>

    </div>

    <div class="list-group">
        {% for artist in artists %}
        
        <div class="row align-items-center">
            <div class="col-1">
                <div class="circle">
                    <p>{{ artist[0].position }}</p>
                </div>
            </div>
            
                
            <div class="col-2">
            <a href="{{ url_for('spotify.art_cat_profile', art_id=artist[0].art_id) }}">
                <img src="https://i.scdn.co/image/{{ artist.img_url_sml }}" title="Que culazo!" class="with-border image-container">
            </a>
            </div>
            
            {% if artist.master_genre == 'rock' %}
            <div class="col-4 rock">
        {% elif artist.master_genre == 'pop' %}
            <div class="col-4 pop">
        {% elif artist.master_genre == 'electronic' %}
            <div class="col-4 electronic">
        {% elif artist.master_genre == 'punk' %}
            <div class="col-4 punk">
        {% elif artist.master_genre == 'funk' %}
            <div class="col-4 funk">
        {% elif artist.master_genre == 'indie' %}
            <div class="col-4 indie">
        {% elif artist.master_genre == 'old' %}
            <div class="col-4 old">
        {% elif artist.master_genre == 'country' %}
            <div class="col-4 country">
        {% else %}
            <div class="col-4">
        {% endif %}
            <a href="https://open.spotify.com/artist/{{ artist[0].art_id }}" class="list-group-item list-group-item-action">
                <b>{{ artist[0].art_name }}</b>
            </a>
            </div>

            <div class="col-5 white-pill">
                {{ artist.genre }}{% if artist.genre2 %}, {{ artist.genre2 }}{% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/spotify/recently_playing.html
{% extends 'base.html' %}

{% block content %}

<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/spotify.css') }}">

<title>The Last Few Songs I Listened To</title>

{% include 'spotify/spotify_header.html' %}

<style>
    .track-col {
        width: 200px;
        margin-right: 20px;
        margin-bottom: 20px; /* Added margin-bottom for space between rows */
        background-color: rgba(196, 238, 219, 0.4); /* 50% transparent */
        border: 1px dotted #028874;
    }

    .track-col:hover {
        background-color: #1a3a30; /* Change this to your desired hover color */
    }

    .known-artist {
        background-color: rgba(0, 162, 255, 0.5); /* Color for known_artist (example: blue) */
    }

    .known-both {
        background-color: rgba(6, 126, 72, 0.8);
        border: 2px dotted #620288; /* Mix of two colors (example: orange) */
    }

</style>

<script>
    // Initialize a variable to track the current page
    var currentPage = {{ pagination.page }};

    $(document).ready(function() {
        $('.load-more-btn').on('click', function() {
            console.log("Button clicked!");

            // Increment the current page for the next request
            currentPage++;

            $.ajax({
                url: '{{ url_for("spotify.right_now") }}?page=' + currentPage,
                method: 'GET',
                success: function(data) {
                    // Append the new content
                    $('#track-container').append($(data).find('#track-container').html());
                },
                error: function(xhr, status, error) {
                    console.error("AJAX Error:", status, error);
                }
            });
        });
    });
</script>

<div class="container">

    <div class="text-center mt-3" style="margin-bottom: 6%;">
        <h2 style="color: #fff;">Endless Stream of What I'm Listening To</h2>
        <h5 style="color: #aaa;">Legend: <span style="background-color: rgba(0, 162, 255, 0.5); padding: 0 10px;">I've Heard of Them</span>,
            <span style="background-color: rgba(6, 126, 72, 0.8); padding: 0 10px;">And I Know This Song</span>
            <span style="background-color: rgba(196, 238, 219, 0.4); padding: 0 10px;">New to the App</span>
        </h5>
    </div>

    <div class="row" id="track-container" style="background-color: #0f1f19; white-space: nowrap;">
        {% for track in last_five %}
        <div class="col track-col 
            {% if track.known_track and track.known_artist %}
                known-both
            {% elif track.known_track %}
                known-track
            {% elif track.known_artist %}
                known-artist
            {% endif %}
        ">
            {{ track.song_name[:35] }}
            <div class="hex">
                <a href="{{ track.song_link }}">
                    <div class="hex-background">
                        <img src="{{ track.image }}" style="max-width: 100%; height: auto;">
                    </div>
                </a>
            </div>
            <div style="display: flex; justify-content: space-between;"> 
                by {{ track.art_name }}
            </div>
        </div>
        {% endfor %}
    </div>
        

    {% if pagination.has_next %}
    <div class="text-center mt-3">
        <button class="load-more-btn btn btn-primary" data-next-page="{{ pagination.next_num }}">Load More</button>
    </div>    
    {% endif %}
</div>

{% endblock %}

app/templates/spotify/spotify_header.html
<style>
    .myDiv {
      color: #fff;
      background-image: linear-gradient(30deg, #17241f, #255743);
      padding: 10px;
      border-radius: 22%;
        background-color: rgb(43, 116, 92);
        border-bottom: 5px solid rgb(22, 59, 47);
        border-top: 3px solid rgb(80, 206, 164);
        }
  
    .myDiv h3 {
      margin-bottom: 20px;
    }
  
    .myDiv-nav {
        display: flex;
        justify-content: center; /* Center justify the navigation links */
    }

    .myDiv-nav a {
      font-size: 12px;
      color: wheat;
      text-decoration: none;
      padding: 12px;
      margin-right: 20px;

    }
  
    .myDiv-nav a:hover {
      color: #1a8678;
      background: #fff;
      border-radius: 20px;

    }
  
    .myDiv-nav .dropdown-menu {
        background-color: rgb(43, 116, 92);
    }

    .myDiv-nav .dropdown-item {
        color: wheat;
        padding: 12px; /* Adjust padding as needed */
        margin-right: 20px; /* Adjust margin as needed */
    }

    .myDiv-nav .dropdown-item:hover {
        color: #1a8678;
        background: #fff;
        border-radius: 20px;
    }

</style>

<div class="container-fluid text-center">
    <div class="myDiv">
      <a href="{{ url_for('spotify.spotify_landing_page') }}">
        <h3 style="color: wheat;">Fred's Spotify Data</h3>
      </a>

        <!-- Navigation Links -->
        <ul class="myDiv-nav nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('spotify.right_now') }}">
                    <i class="fa fa-bolt" aria-hidden="true"></i>
                    Right Now
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('spotify.yesterday') }}">
                    <i class="fa fa-clock" aria-hidden="true"></i>
                    Yesterday
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="https://fredlambuth.com/spotify/big_dash/">
                    <i class="fa fa-chart-line" aria-hidden="true"></i>
                    Weekly
                </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="https://fredlambuth.com/spotify/monthly/{{ g.current_year}}/{{ g.current_month - 1 }}">
                  <i class="fa fa-calendar" aria-hidden="true"></i>
                  Monthly
              </a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="catalogDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-list" aria-hidden="true"></i>
                  Catalog
              </a>
          
              <!-- Dropdown Menu -->
              <div class="dropdown-menu" aria-labelledby="catalogDropdown" style="width: 120px;">
                  <a class="dropdown-item" href="{{ url_for('spotify.art_cat_landing_page') }}">Artists</a>                
                  <a class="dropdown-item" href="{{ url_for('spotify.track_cat_landing_page') }}">Tracks</a>
                  <a class="dropdown-item" href="{{ url_for('spotify.genres_landing_page') }}">Genres</a>
              </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="todayDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-archive" aria-hidden="true"></i>
                    Archives
                </a>

                <!-- Dropdown Menu -->
                <div class="dropdown-menu" aria-labelledby="todayDropdown" style="width: 120px;">
                    <a class="dropdown-item" href="{{ url_for('spotify.latest_daily_artists') }}">Artists</a>
                    <a class="dropdown-item" href="{{ url_for('spotify.latest_daily_tracks') }}">Tracks</a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="https://fredlambuth.com/spotify/global/">
                    <i class="fa fa-globe" aria-hidden="true"></i>
                    Global Stats
                </a>
            </li>
        </ul>
    </div>
</div>

app/templates/spotify/spotify_homepage.html
{% extends 'base.html' %}

{% block content %}
<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/spotify.css') }}">
<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/blog.css') }}">

<title>Landing Page for Spotify Stuff</title>

{% include 'spotify/spotify_header.html' %}

<style>
    /* General styles */
    .image-container {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 175px;
    }

    .image-container img {
        width: 100%;
        object-fit: fill;
    }

    .w3-card,
    .w3-row {
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
        background-color: rgba(255, 255, 255, 0.03);
        padding: 10px;
        border-radius: 5%;
    }

    .w3-card:hover {
        background-color: #1c1f03;
        transition: background-color 0.3s ease;
    }

</style>

<body style="background-color: #000c0a;">

<div class="w3-content" style="max-width:1400px; padding: 50px;">
    <div class="w3-row">

        <div class="w3-col l8 s12">
            <div class="w3-card w3-margin w3-margin-top">
                <div class="image-container">
                <img src="{{url_for('static', filename='img/detroit.jpg')}}" alt="Unknown Detroit Bluesman" title="Robert Crumb cover of Unknown Detroist Bluesman. 1970.">
            </div>
            
            <div class="w3-container w3-teal">
                <h2>Welcome to the Spotify section of the website!</h2>
            </div>
            <p style="text-align: center;">Everyday I collect my listening data from Spotify. This section has views into what I was listening to on what day.</p>
        </div>
            
        <div class="row">
            <a href="{{ url_for('spotify.top_five_artist_plot') }}" title="Scatter Plot of Top 5 Artist History">
            <div class="w3-card w3-margin">
                <h2>Most Played Artists:</h2>
                {% for art in top_5_arts %}
                    <div>{{ art[0] }} <span style="color: aliceblue;">{{ art[1] }}</span></div>
                {% endfor %}
            </div>
            </a>
            
            <a href="{{ url_for('spotify.top_five_tracks_plot') }}" title="Scatter Plot of Top 5 Artist History">
            <div class="w3-card w3-margin">
                <h2>Most Played Tracks:</h2>
                {% for track in top_5_tracks %}
                    <div>{{ track[0] }} <span style="color: aliceblue">{{ track[1] }}</span></div>
                {% endfor %}
            </a>
            </div>
        </div>        
    </div>

    <div class="w3-col l4" style="padding-right: 20px;">
        <div class="w3-card w3-margin w3-margin-top">
            <h2 style="margin-right: 30px;">Average Song Count per Day: <span class="white-pill">{{ daily_rp_avg }}</span></h2>
        </div>
        
        <div>
            <h2>Newest Additions:</h2>
            
            {% for new_artist in latest_artists %}
            <div class="row mb-3" style="background-color: #012b25; border-radius: 12%; border: solid 2px #028874; padding-right: 19px;">
                
                <div class="col-md-10" style="color: wheat; padding-left: 50px;">
                    <a href="https://open.spotify.com/artist/{{ new_artist.art_id }}">
                        <h5>{{ new_artist.art_name }}</h5>
                    </a>
                    <p>
                        {% if new_artist.genre2 %}
                            <a href="{{ url_for('spotify.index_by_genre', master_genre=new_artist.genre) }}">{{ new_artist.genre }}</a>,
                            <a href="{{ url_for('spotify.index_by_genre', master_genre=new_artist.genre2) }}">{{ new_artist.genre2 }}</a>
                        {% else %}
                            <a href="{{ url_for('spotify.index_by_genre', master_genre=new_artist.genre) }}">{{ new_artist.genre }}</a>
                        {% endif %}
                    </p>
                    
                </div>
                <div class="col-md-2 d-flex ml-auto">
                    <img src="https://i.scdn.co/image/{{ new_artist.img_url_sml }}" alt="Tiny Image" class="circular-image">
                </div>
            </div>
            {% endfor %}
        </div>
        
    </div>
</div>


{% endblock %}