app/models/blog.py
from app.extensions import db
#from app import login_manager
from datetime import datetime
#from flask_login import UserMixin
from sqlalchemy import func
#from werkzeug.security import check_password_hash, generate_password_hash

def convert_to_iso_date(date_string):
    return datetime.strptime(date_string, '%Y-%b-%d').isoformat()[:10]

class blog_posts(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(150), nullable=False)
    content = db.Column(db.Text, nullable=False)
    post_date = db.Column(db.String(20), nullable=False)
    medium = db.Column(db.String(50))
    theme1 = db.Column(db.String(50))
    theme2 = db.Column(db.String(50))

    @property
    def iso_date(self):
        return convert_to_iso_date(self.post_date)
    
    @classmethod
    def last_post_id(cls):
        last_id = cls.query.with_entities(cls.id).all()[-1][0]
        return last_id

    @classmethod
    def mediums_index(cls):
        medium_counts = db.session.query(
            cls.medium, func.count()
            ).group_by(cls.medium).order_by(func.count().desc()).all()
        return medium_counts

    @classmethod
    def year_month_blogpost_index(cls):
        result = (
            db.session.query(
                func.substr(cls.post_date, 1, 8).label('year_month'),
                func.count().label('post_count')
            )
            .group_by('year_month')
            .order_by('year_month')  # Optional: Order the results by year-month
            .all()
        )

        #does a quick sort by changing the 2023-JAN string to a measurable date 
        datetime_result = [(datetime.strptime(i[0], '%Y-%b'),i[1]) for i in result]
        sorted_data = sorted(datetime_result, key=lambda x: x[0])
        sorted_strings = [(datetime.strftime(date_str, "%Y-%b"), post_count) for date_str, post_count in sorted_data]
        return sorted_strings

    @classmethod
    def year_of_blog_posts(cls):
        result = (
            db.session.query(
                func.substr(cls.post_date, 1, 4).label('year'),
                func.count().label('post_count')
            )
            .group_by('year')
            .order_by('year')  # Optional: Order the results by year-month
            .all()
        )

        #does a quick sort by changing the 2023-JAN string to a measurable date 
        #datetime_result = [(datetime.strptime(i[0], '%Y-%b'),i[1]) for i in result]
        #sorted_data = sorted(datetime_result, key=lambda x: x[0])
        #sorted_strings = [(datetime.strftime(date_str, "%Y-%b"), post_count) for date_str, post_count in sorted_data]
        return result

    def __repr__(self):
        return f'<Post "{self.title}">'

app/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog', __name__)

from app.blog import routes

app/blog/routes.py
from app.blog import bp
from app.forms import SearchForm, CommentForm, SubmitBlogForm, SubmitPictureForm
from app.models.blog import blog_posts
from app.models.accounts import blog_comments
from app.models.charts import daily_tracks
from app.extensions import db
from app.utils import resize_image, resize_imageOLD

from my_spotipy import spotify_object

import os
from werkzeug.utils import secure_filename
from werkzeug.exceptions import RequestEntityTooLarge
from datetime import datetime
from sqlalchemy import desc, func
from flask_login import login_required, current_user
from flask import render_template, request, redirect, url_for, flash, current_app

from datetime import date
#################################################
@bp.route('/blog', methods=['GET', 'POST'])
@bp.route('/blog/', methods=['GET', 'POST'])
def blog_landing_page():
    current_year = str(date.today().year)
    searchform = SearchForm()
    if request.method == 'POST':
        return redirect(url_for('blog.blog_index_search', search_term=searchform.search_term.data))
    latest_3_posts = blog_posts.query.order_by(desc(blog_posts.id)).limit(3).all()

    all_yearmonths_index = blog_posts.year_month_blogpost_index()
    this_yearmonths_index = [i for i in all_yearmonths_index if i[0][:4]==current_year]

    all_years_index = blog_posts.year_of_blog_posts()
    prev_years_index = [i for i in all_years_index if i[0]!=current_year]

    medios_index = blog_posts.mediums_index()

    context = {
        'year_month_index' : this_yearmonths_index,
        'prev_years_index' : prev_years_index,
        'mediums_index' : medios_index,
        'latest_3_posts' : latest_3_posts,
        'form':searchform,
    }
    return render_template('blog/blog_landing_page.html', **context)

@bp.route('/blog/<string:year_month>', methods=['GET', 'POST'])
def blog_yearmonth_group(year_month):
    searchform = SearchForm()
    if request.method == 'POST':
        return redirect(url_for('blog.blog_index_search', search_term=searchform.search_term.data))
    posts = blog_posts.query.filter(blog_posts.post_date.like(f'{year_month}%')).all()

    context = {
        'posts' : posts,
        'form':searchform,
    }
    return render_template('blog/blog_index.html', **context)

@bp.route('/blog/year/<string:year>', methods=['GET', 'POST'])
def blog_year_group(year):
    per_page = 6
    # Get the current page from request arguments, defaulting to 1
    page = request.args.get('page', 1, type=int)

    searchform = SearchForm()
    if request.method == 'POST':
        return redirect(url_for('blog.blog_index_search', search_term=searchform.search_term.data))
    posts = blog_posts.query.filter(
        func.substr(blog_posts.post_date, 1, 4) == year
    ).paginate(
        page=page,
        per_page=per_page,
        error_out=False,
    )

    context = {
        'posts' : posts.items,
        'form':searchform,
        'page': page,
        'year': year,
        'total_pages': posts.pages,
        'prev_page': posts.prev_num,
        'next_page': posts.next_num,
    }
    return render_template('blog/blog_index.html', **context)

@bp.route('/blog/review/<string:medium>', methods=['GET', 'POST'])
def blog_about_this_medium(medium):
    per_page = 6
    # Get the current page from request arguments, defaulting to 1
    page = request.args.get('page', 1, type=int)

    searchform = SearchForm()
    if request.method == 'POST':
        return redirect(url_for('blog.blog_index_search', search_term=searchform.search_term.data))
    
    #posts = blog_posts.query.filter(blog_posts.medium == medium).all()
    paginated_posts = blog_posts.query.filter(blog_posts.medium == medium).order_by(
        desc(blog_posts.id)
    ).paginate(
        page=page,
        per_page=per_page,
        error_out=False,
    )

    context = {
        'posts': paginated_posts.items,
        'form': searchform,
        'page': page,
        'medium': medium,
        'total_pages': paginated_posts.pages,
        'prev_page': paginated_posts.prev_num,
        'next_page': paginated_posts.next_num,
    }
    return render_template('blog/blog_index.html', **context)



@bp.route('/blog/search/<string:search_term>', methods=('GET','POST'))
@login_required
def blog_index_search(search_term):
    searchform = SearchForm()
    if request.method == 'POST':
        return redirect(url_for('blog.blog_index_search', search_term=searchform.search_term.data))

    blogs_like = blog_posts.content.like(f"%{search_term}%")
    blog_matches = blog_posts.query.filter(blogs_like).order_by(desc('id')).all()

    context = {
        'posts':blog_matches,
        'form':searchform,
    }

    return render_template('blog/blog_index.html', **context)

########
@bp.route('/blog/post/<int:post_id>', methods=['GET', 'POST'])
def blog_single(post_id):
    searchform = SearchForm()
    if request.method == 'POST':
        return redirect(url_for('blog.blog_index_search', search_term=searchform.search_term.data))
    max_id = db.session.query(func.max(blog_posts.id)).all()[0][0]
    if post_id==max_id:
        next_post=None
    else:
        next_post = blog_posts.query.filter(blog_posts.id==post_id+1).all()[0]
    post = blog_posts.query.filter(blog_posts.id==post_id).all()[0]

    if post_id==1:
        prev_post=None
    else:
        prev_post = blog_posts.query.filter(blog_posts.id==post_id-1).all()[0]

    top_3_songs = daily_tracks.random_n_tracks_that_day(post.iso_date)
    post_comments = blog_comments.query.filter_by(post_id=post_id).all()

    context = {
        'post' : post,
        'prev_post' : prev_post,
        'next_post' : next_post,
        'top_3_songs' : top_3_songs,
        'form':searchform,
        'comments': post_comments,
    }
    return render_template('blog/blog_single.html', **context)

#####################
###comments
@bp.route('/blog/add_comment/<int:post_id>', methods=['GET', 'POST'])
@login_required
def blog_add_comment(post_id):
    form = CommentForm()
    post = blog_posts.query.filter(blog_posts.id==post_id).all()[0]

    if form.validate_on_submit():
        new_comment = blog_comments(
            content=form.content.data,
            post_id=post_id,
            user_id=current_user.id,
            comment_date=datetime.utcnow()
        )

        db.session.add(new_comment)
        db.session.commit()

        flash('Your comment has been added!', 'success')
        return redirect(url_for('blog.blog_single', post_id=post_id))

    return render_template('blog/blog_add_comment.html', post=post, form=form)

@bp.route('/upload_blog_post', methods=['GET', 'POST'])
@login_required
def submit_blog_post():
    #UPLOAD_FOLDER = '/static/img/blog_pics/'
    #ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
    
    form = SubmitBlogForm()
    latest_blog_id = str(blog_posts.last_post_id() + 1)
    test_file_name = f'pic_{latest_blog_id}.jpg'
    filename = secure_filename(test_file_name)
    print(filename)

    blog_pic_dir = '/home/flambuth/fredlambuthPUNTOcom/app/static/img/blog_pics/'
    
    if current_user.username != 'eddie_from_chicago':
        flash("You are not authorized to submit a blog post.")
        return redirect(url_for('user_accounts.login'))

    if form.validate_on_submit():

        print("Form data:", form.data)

        
        if form.picture.data:

            input_path = blog_pic_dir + filename
            print("File to be Saved:", input_path)
            form.picture.data.save(input_path)
            print("File saved to input path")

        new_post = blog_posts(
            title=form.title.data,
            content=form.content.data,
            medium=form.medium.data.lower(),
            post_date=datetime.today().strftime('%Y-%b-%d'))

        db.session.add(new_post)
        db.session.commit()

        
        return redirect(url_for('blog.blog_landing_page'))

    else:
        # Form submission failed validation
        # Print validation errors
        for field, errors in form.errors.items():
            for error in errors:
                flash(f"Error in field '{field}': {error}")
                print(f"Error in field '{field}': {error}")
        return render_template('blog/blog_add_post.html', title='Register', form=form)
    


#################################################
@bp.route('/blog/amy', methods=['GET', 'POST'])
def amy_landing_page():
    current_year = str(date.today().year)
    searchform = SearchForm()
    if request.method == 'POST':
        return redirect(url_for('blog.blog_index_search', search_term=searchform.search_term.data))

    filepath = os.path.join(current_app.static_folder, 'amy.txt')
    with open(filepath, 'r') as file:
        content = file.read()

    amy_5_songs = spotify_object.amys_last_five_songs_recently_played()

    context = {
        'amy_5_songs' : amy_5_songs,
        'blog_post' : content,
        'form':searchform,
    }
    return render_template('blog/amy_landing_page.html', **context)

app/templates/blog/blog_add_comment.html
{% extends 'base.html' %}

{% block content %}
<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/blog.css') }}">
<title>Make It Simple But Significant</title>
<body class="w3-black">

  <div class="container">
    <h2>Add Comment</h2>
    <form method="post" action="{{ url_for('blog.blog_add_comment', post_id=post.id) }}">
      {{ form.hidden_tag() }}
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.content.label(class="form-control-label") }}
        {{ form.content(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>
  </div>

{% endblock %}

app/templates/blog/blog_add_post.html
{% extends "base.html" %}
{% block content %}

<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/blog.css') }}">
<title>Oof!</title>

<body class="w3-black">
    <div class="container" style="width: 66%;">
        {{ form.hidden_tag() }}
        <h2>Register</h2>
        {% for message in get_flashed_messages() %}
            <div class="alert alert-info" role="alert">
                {{ message }}
            </div>
        {% endfor %}
        <form method="post" action="{{ url_for('blog.submit_blog_post') }}" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {{ form.title(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {{ form.content(class="form-control", rows=10) }}
            </div>
            <div class="form-group">
                {{ form.medium.label(class="form-control-label") }}
                {{ form.medium(class="form-control") }}
            </div>

            

            <div class="form-group">
                {{ form.picture.label(class="form-label") }}
                <div class="custom-file">
                    {{ form.picture(class="custom-file-input", id="customFile") }}
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
            </div>

            <button type="submit" class="btn btn-primary">Add Post</button>
        </form>
    </div>
    
    <script>
        // Update the label text when a file is selected
        document.getElementById("customFile").addEventListener("change", function() {
            var fileName = this.value.split("\\").pop();
            this.nextElementSibling.innerHTML = fileName;
        });
    </script>
{% endblock %}

app/templates/blog/blog_header.html
<style>
    .hover-effect:hover {
        color: rgb(115, 255, 0); /* Change this to your desired hover color */
        transition: color 0.3s ease; /* Adjust the transition speed as needed */
    }

    .outlined-text {
        color: wheat;
        text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;
    }
</style>

<br>
<header class="w3-container w3-center w3-padding-32;" 
style="background-color: #238a6b; border-radius: 28%; border: 2px solid palegreen;"> 
    <h1 class="outlined-text"><b>Fred<span class="hover-effect"> and Loathing on The Internet</span></b></h1>
    <p>Welcome to the public web log of <a href="{{ url_for('blog.blog_landing_page') }}"><span class="w3-tag">Fred Lambuth</span></a></p>
    <form method="POST" >
        <p style="color: wheat;" title="Search Through Blog Posts">
            {{ form.search_term.label }}
            {{ form.search_term(size=20) }}
        </p>
    </form>
</header>

app/templates/blog/blog_index.html
{% extends 'base.html' %}

{% block content %}

<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/blog.css') }}">
<head>

    <title>Fred's Blog</title>

<style>

</style>
</head>

<body class="w3-black">


{% include 'blog/blog_header.html' %}
<br>
<div class="container">
    {% for post in posts %}
    <div class="w3-card-4 w3-margin w3-pale-green" >
                
        <div class="row w3-teal" style="border-bottom: 3px solid palegreen;">
            <div class="col-left">
                <a href="{{ url_for( 'blog.blog_single', post_id=post.id) }}">
                <img src="{{url_for('static', filename='img/blog_pics/pic_' + post.id|string + '.jpg')}}" width="80" title="Rando off the street." class="circular-image">
                
            </div>
            <div class="col-right">
                <h3><b>{{ post.title }}</b></h3></a>
                <h5><span class="w3-opacity date-pill">{{ post.post_date }}</span></h5>
            </div>
        </div>

        <br>

        <div class="w3-container center-text">
            <p>{% autoescape false %} {{ post.content | replace('\n', '<br>') | truncate(300)}} {% endautoescape %}</p>
        </div>
    </div>
    <hr>
    {% endfor %}
</div>


{% if medium %}
    {% if next_page or prev_page %}
    <div class="mt-3 d-flex" style="justify-content: center;">
        {% if prev_page %}
        <span>
            <a class='prev-post btn btn-secondary' href="{{ url_for('blog.blog_about_this_medium', medium=medium, page=prev_page) }}">
                {{ 'Previous' }}
            </a>
        </span>
        {% endif %}
        {% if next_page and prev_page %} || {% endif %}
        {% if next_page %}
        <span>
            <a class='next-post btn btn-secondary' href="{{ url_for('blog.blog_about_this_medium', medium=medium, page=next_page) }}">
                {{ 'Next' }}
            </a>
        </span>
        {% endif %}

    </div>
    {% endif %}
{% endif %}

{% if year %}
    {% if next_page or prev_page %}
    <div class="mt-3 d-flex" style="justify-content: center;">
        {% if prev_page %}
        <span>
            <a class='prev-post btn btn-secondary' href="{{ url_for('blog.blog_year_group', year=year, page=prev_page) }}">
                {{ 'Previous' }}
            </a>
        </span>
        {% endif %}
        {% if next_page and prev_page %} || {% endif %}
        {% if next_page %}
        <span>
            <a class='next-post btn btn-secondary' href="{{ url_for('blog.blog_year_group', year=year, page=next_page) }}">
                {{ 'Next' }}
            </a>
        </span>
        {% endif %}

    </div>
    {% endif %}
{% endif %}

{% endblock %}

app/templates/blog/blog_landing_page.html
{% extends 'base.html' %}

{% block content %}

<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/blog.css') }}">

<title>Fear and Loathing on The Internet</title>

<body class="w3-black">

    <!-- w3-content defines a container for fixed size centered content, 
    and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1400px">
    
    <!-- Header -->
    {% include 'blog/blog_header.html' %}
    
    <!-- Grid -->
    <div class="w3-row">
    
        <!-- Introduction menu -->
        <div class="w3-col l4">
            <!-- About Card -->
            <div class="w3-card w3-margin w3-margin-top">
                <img src="{{url_for('static', filename='img/sailor.jpg')}}" title="CS2 Peter Grabnickas, a crew member of the USS Capelin, disappeared with the ship in the Celebes Sea near Indonesia on Dec 2, 1943. Photo taken two months before the submarine's last known sighting.">
                <div class="w3-container w3-teal">
                    <p>This is the blog! I talk about books, video games, movies and podcasts of all types. It's not much, but it's honest work.</p>
                </div>
            </div>
            
            <hr>
            
            <!-- Posts -->
            <div class="w3-card w3-margin">
                <div class="w3-container w3-padding w3-teal">
                <h4>Topics</h4>
                </div>
                
                <ul class="w3-ul w3-hoverable w3-white" style="margin-top: 0; margin-bottom: 0;">
                    {% for media_type in mediums_index %}
                    <li class="w3-padding-8" style="display: flex; justify-content: space-between;">
                        <a href="{{url_for('blog.blog_about_this_medium', medium=media_type[0])}}" style="text-decoration: none;">
                            <span class="w3-medium">{{ media_type[0] }}</span>
                        </a>
                        <span>{{ media_type[1] }} posts</span>
                    </li>
                    {% endfor %}
                </ul>

            </div>

            <div class="w3-card w3-margin">
                <div class="w3-container w3-padding w3-teal">
                    <h4>Archives</h4>
                </div>
                
                <!-- Month-level archives -->
                <ul class="w3-ul w3-hoverable w3-white" style="margin-top: 0; margin-bottom: 0;">
                    {% for year_month in year_month_index[::-1] %}
                    <li class="w3-padding-8" style="display: flex; justify-content: space-between;">
                        <a href="{{url_for('blog.blog_yearmonth_group', year_month=year_month[0])}}" style="text-decoration: none;">
                            <span class="w3-medium">{{ year_month[0] }}</span>
                        </a>
                        <span>{{ year_month[1] }} posts</span>
                    </li>
                    {% endfor %}
                </ul>
                
                <!-- Year-level archives -->
                <ul class="w3-ul w3-hoverable w3-white" style="margin-top: 0; margin-bottom: 0;">
                    {% for year_count in prev_years_index %}
                    <li class="w3-padding-8" style="display: flex; justify-content: space-between;">
                        <a href="{{ url_for('blog.blog_year_group', year=year_count[0]) }}" style="text-decoration: none;">
                            <span class="w3-medium">{{ year_count[0] }}</span>
                        </a>
                        <span>{{ year_count[1] }} posts</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            
            <hr> 
            
            <!-- END Introduction Menu -->
        </div>
    
        <!-- Blog entries -->
        <div class="w3-col l8 s12">
            <!-- Blog entry -->
            {% for post in latest_3_posts %}
            <div class="w3-card-4 w3-margin w3-pale-green ">
                
                <div class="row w3-teal" style="border-bottom: 3px solid palegreen;">
                    <div class="col-left">
                        <a href="{{ url_for( 'blog.blog_single', post_id=post.id) }}">
                        <img src="{{url_for('static', filename='img/blog_pics/pic_' + post.id|string + '.jpg')}}" width="80" title="Rando off the street." class="circular-image">
                        
                    </div>
                    <div class="col-right">
                        <h3 class="outlined-text"><b>{{ post.title }}</b></h3></a>
                        <h5><span class="w3-opacity date-pill">{{ post.post_date }}</span></h5>
                    </div>
                </div>

                <br>

                <div class="w3-container center-text" style="padding: 35px;">
                    <p>{% autoescape false %} {{ post.content | replace('\n', '<br>') | truncate(1500)}} {% endautoescape %}</p>
                </div>
            </div>
            <hr>
            {% endfor %}
            <!-- END BLOG ENTRIES -->
        </div>
    <!-- END GRID -->
    </div><br>
    
    <!-- END w3-content -->
</div>
    
    
    </body>

{% endblock %}

app/templates/blog/blog_single.html
{% extends 'base.html' %}

{% block content %}

<title>Blog Post: {{ post.title }}</title>

<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/blog.css') }}">
<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/spotify.css') }}">

<style>
    .list-group-item {
        color: #000; 
        background-color: #fff; 
    }

    .list-group-item:hover {
        color: #fff; 
        background-color: #296c6e; 
    }

    .list-group-item.list-group-item-primary {
        color: #fff; 
        background-color: #023022; 
    }


    .comment {
        background-color: #296c6e;
        padding: 10px;
        margin-bottom: 10px;
        border-radius: 7%;
        border: 1px solid wheat;
    }

    .comment p {
        background-color: wheat;
        color: #020f0b;
        padding: 10px;
        border-radius: 5%; 
    }

    .comment img {
        width: 80px;
        height: 80px;
        border: 2px solid #43f1d4;
        
    }

    .comment small {
        color: wheat;
    }

    .image-container-double {
        border: 10px double #023022;
        border-radius: 5%;
    }
</style>



<body class="w3-black">

<div class="container" style="width: 92%;">
        
    {% include 'blog/blog_header.html' %}

    <div class="mt-3 d-flex justify-content-center">
        {% if next_post %}
            <span>
                <a class='next-post btn btn-secondary' href="{{url_for('blog.blog_single', post_id=next_post.id ) }}">
                    {{ 'Next' }}
                </a>
            </span>
        {% endif %}
        {% if next_post and prev_post %} || {% endif %}
        {% if prev_post %}
            <span>
                <a class='prev-post btn btn-secondary' href="{{url_for('blog.blog_single', post_id=prev_post.id ) }}">
                    {{ 'Previous' }}
                </a>
            </span>
        {% endif %}
    </div>
    
    <hr>
    <div class="row">
        <div class="col-md d-flex align-items-center justify-content-center">
            <img src="{{url_for('static', filename='img/blog_pics/pic_' + post.id|string + '.jpg')}}" 
                 width="360" 
                 title="Rando off the street." 
                 style="border: 3px solid #020f0b; border-radius: 5%; box-shadow: 0 0 0 6px #023022, 0 0 0 7px wheat;">
        </div>
        <div class="col" style="padding: 5px;"> 
            <section class="text-end w3-teal w3-margin-top"> 
                <div class="list-group">
                    <h6 class="list-group-item list-group-item-primary">Popular Tracks from {{ post.iso_date }}</h6>
                    {% for track in top_3_songs %}
                        <a href="https://open.spotify.com/track/{{ track.song_id }}" class="list-group-item d-flex justify-content-between align-items-center">
                        <div>
                            <b>{{ track.song_name }}</b> by <b>{{ track.art_name }}</b>
                        </div>

                    </a>
                    {% endfor %}
                </div>
            </section>
        </div>
    </div>
    <hr>
    <div class="w3-container w3-pale-green" style="border: solid 4px #296c6e; padding: 5px; display: flex; align-items: center;">
        <h4 style="margin: 0;"><b>{{ post.title }}</b></h4>
        <h5 class="date-pill" style="margin-left: auto;">
            <a href="{{ url_for('spotify.tracks_prev', year=post.iso_date.split('-')[0], month=post.iso_date.split('-')[1], day=post.iso_date.split('-')[2]) }}" title="Link to Spotify charts on this day">
                {{ post.post_date }}
            </a>
        </h5>
    </div>
    <br>
    

        <div class="w3-container w3-pale-green" style="border: solid 4px #296c6e; padding: 35px;">
            <p>{% autoescape false %} {{ post.content | replace('\n', '<br>') }} {% endautoescape %}</p>
        </div>
    <hr>

    {% for comment in comments %}
    <div class="comment">
        <div class="row">
            <div class="col-2 text-center">
                <img src="{{ url_for('static', filename='img/user_pics/' + comment.user.username + '.jpg') }}" alt="One of our lovely Fredlambuth.com users!" class="circular-image">
                <br>
                <small>{{ comment.user.username }}</small>
            </div>
            <div class="col-10">
                <p>{{ comment.content }}</p>
                <small>{{ comment.comment_date }}</small>
            </div>
        </div>
    </div>
    {% endfor %}

    <a href="{{ url_for('blog.blog_add_comment', post_id=post.id) }}" class="btn btn-primary" title="You Know You Wanna">Add Comment</a>

    <!-- Next and Previous Post Links -->
    {% if next_post or prev_post %}
        <div class="mt-3">
            {% if next_post %}
                <span>
                    <a class='next-post btn btn-secondary' href="{{url_for('blog.blog_single', post_id=next_post.id ) }}">
                        {{ 'Next' }}
                    </a>
                </span>
            {% endif %}
            {% if next_post and prev_post %} || {% endif %}
            {% if prev_post %}
                <span>
                    <a class='prev-post btn btn-secondary' href="{{url_for('blog.blog_single', post_id=prev_post.id ) }}">
                        {{ 'Previous' }}
                    </a>
                </span>
            {% endif %}
        </div>
    {% endif %}
</div>
<br>
</div>




{% endblock %}