app/spotify/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import InputRequired, Length


class CourseForm(FlaskForm):
    search_term = StringField('Search: ', validators=[InputRequired(),
                                             Length(min=1, max=100)])

app/spotify/__init__.py
from flask import Blueprint
from app.spotify.cache import cache

bp = Blueprint('spotify', __name__)

from app.spotify import routes

app/spotify/routes.py
from app.spotify import bp, cache
from flask import render_template, request, redirect, url_for, render_template_string, flash
from flask_login import login_required, current_user
from sqlalchemy import desc

from app.models.charts import recently_played, daily_artists ,daily_tracks
from app.models.catalogs import track_catalog, artist_catalog
from app.models.playlists import Playlists
from app.models.accounts import artist_comments

from app import db

from app.dash_plotlys.plotly_figures import chart_scatter_plotly

from app.spotify.forms import CourseForm
from app.forms import CommentForm, SearchForm

import app.spotify.daily_funcs as daily_funcs
import app.spotify.art_cat_funcs as ac_funcs
from app.spotify.plotly_figs import top_5_artists_fig, top_5_tracks_fig


from datetime import datetime

#YOU CANT HAVE ANYTHING OUTSIDE OF DECORATED ROUTES! Do it somewhere else and import it.
#latest_daily_date = daily_tracks.query.order_by(daily_tracks.id.desc()).first().date
#latest_date_obj = datetime.strptime(latest_daily_date, "%Y-%m-%d").date()


###############################
##Playlists
#@bp.route('/spotify/playlist/<string:playlist_id>', methods=('GET','POST'))
@bp.route('/spotify/playlist', methods=('GET','POST'))
def playlist_homepage():
    '''
    Temp install!
    '''
    #fig = top_5_artists_fig()
    #html = fig.to_html()

    return render_template('spotify/playlist/playlist_timeline.html')

@bp.route('/spotify/playlist/<string:playlist_id>', methods=('GET','POST'))
def playlist_timeline(playlist_id):
    '''
    Temp install!
    '''
    playlist_records = Playlists.filtered_enriched_playlist(playlist_id)
    
    context = {
        'tracks':playlist_records,
    }

    return render_template('spotify/playlist/playlist_timeline.html', **context)


##############################
@bp.route('/spotify/top_five_artists')
@login_required
def top_five_artist_plot():
    '''
    Temp install!
    '''
    fig = top_5_artists_fig()
    html = fig.to_html()

    return render_template_string(html)

@bp.route('/spotify/top_five_tracks')
@login_required
def top_five_tracks_plot():
    '''
    No sidebar!
    '''
    fig = top_5_tracks_fig()
    html = fig.to_html()

    return render_template_string(html)


#############################################
@bp.route('/spotify')
@bp.route('/spotify/')
def spotify_landing_page():
    '''
    I guess this should look flashy and have a menu that offers something the sidebar of the regular Spotify
    views or the art_cat_base do not offer. Or just a very simple menu, but flashier?
    '''
    latest_5 = ac_funcs.latest_art_cats()
    top_5_arts = daily_funcs.top_ever_daily_artists(5)
    top_5_tracks = daily_funcs.top_ever_daily_tracks(5)
    daily_rp_avg = recently_played.rp_average_per_day()

    context = {
        'latest_artists':latest_5,
        'top_5_arts' : top_5_arts,
        'top_5_tracks' : top_5_tracks,
        'daily_rp_avg' : daily_rp_avg,
        
    }
    return render_template('spotify/spotify_homepage.html', **context)


###########################################
# art_cat routes

@bp.route('/spotify/art_cat/', methods=('GET','POST'))
@bp.route('/spotify/art_cat', methods=('GET','POST'))
def art_cat_landing_page():
    form = CourseForm()
    #if form.validate_on_submit():
    if request.method == 'POST':
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))

    thruples = ac_funcs.genre_landing_thruples()

    context = {
        'thruples' : thruples,
        'form':form,
    }

    return render_template('spotify/art_cat/art_cat_landing.html', **context)


# Adding Comments to artist
@bp.route('/spotify/art_cat/artist/<string:art_id>', methods=('GET','POST'))
def art_cat_profile(art_id):
    form = SearchForm()
    comment_form = CommentForm()

    if (form.validate_on_submit()):
        print('search bar was used')
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))
    
    
    if comment_form.validate_on_submit():
        print('comment was made')
        if not current_user.is_authenticated:
            flash('You must be logged in to add a comment.', 'warning')
            return redirect(url_for('user_accounts.login'))  # Redirect to login page if not logged in
        
        art_comment = artist_comments(
            content=comment_form.content.data,
            artist_catalog_id=art_id,
            user_id=current_user.id,
            comment_date=datetime.utcnow())
        
        db.session.add(art_comment)
        db.session.commit()
        return redirect(url_for('spotify.art_cat_profile', art_id=art_id))

    profile_context = ac_funcs.art_cat_profile(art_id)
    profile_context['form'] = form
    profile_context['comment_form'] = comment_form

    print('profile got GET')
    return render_template('spotify/art_cat/art_cat_profile.html', **profile_context)

#######################
#Three index routes. They need pagination.
#How?

@bp.route('/spotify/art_cat/<string:letter>', methods=('GET','POST'))
def index_by_letter(letter):
    page = request.args.get('page', 1, type=int)
    form = CourseForm()
    #if form.validate_on_submit():
    if request.method == 'POST':
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))
    
    art_cat_index, total_count = ac_funcs.all_art_cats_starting_with(
        letter,
        page,
        )
    
    context = {
        'art_cat_index' : art_cat_index.items,
        'letter' : letter,
        'form':form,
        'artist_count': total_count,
        'prev_page':art_cat_index.prev_num,
        'next_page':art_cat_index.next_num,
        'first_page':1,
        'last_page':art_cat_index.pages,
    }

    return render_template('spotify/art_cat/art_cat_index.html', **context)



@bp.route('/spotify/art_cat/genre/<string:master_genre>', methods=('GET','POST'))
@bp.route('/spotify/art_cat/genre', defaults={'master_genre': None}, methods=('GET','POST'))
def index_by_genre(master_genre):
    page = request.args.get('page', 1, type=int)
    form = CourseForm()
    #if form.validate_on_submit():
    if request.method == 'POST':
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))
    
    sort = request.args.get('sort','default')

    if (master_genre in ac_funcs.genres)|(master_genre is None) :
        art_cat_index, ac_count = ac_funcs.all_art_cats_in_master_genre(
            master_genre, 
            page,
            sort
            )    
    else:
        art_cat_index, ac_count = ac_funcs.art_cats_with_this_genre(
            master_genre, 
            page,
            sort,
            )


    context = {
        'genre': master_genre,
        'artist_count': ac_count,
        'art_cat_index': art_cat_index.items,
        'form':form,
        'prev_page':art_cat_index.prev_num,
        'next_page':art_cat_index.next_num,
        'first_page':1,
        'last_page':art_cat_index.pages,
        'sort':sort,
    }

    return render_template('spotify/art_cat/art_cat_index.html', **context)

@bp.route('/spotify/search/<string:search_term>', methods=('GET','POST'))
def index_by_search(search_term):
    form = CourseForm()
    if request.method == 'POST':
        return redirect(url_for('spotify.index_by_search', search_term=form.search_term.data))

    like_arts = ac_funcs.art_cat_name_search(search_term)

    context = {
        'like_arts':like_arts,
        'form':form,
    }

    return render_template('spotify/art_cat/art_cat_search.html', **context)

###########################################
###########################################
#track_cat routes

@bp.route('/spotify/track_cat/', methods=('GET','POST'))
@bp.route('/spotify/track_cat', methods=('GET','POST'))
def track_cat_landing_page():

    thruples = track_catalog.track_cat_landing_thruples()

    context = {
        'thruples' : thruples,
    }

    return render_template('spotify/track_cat/track_cat_landing.html', **context)

@bp.route('/spotify/track_cat/<string:letter>')
def index_tracks_by_letter(letter):
    
    track_index = track_catalog.all_tracks_starting_with(letter)
    
    context = {
        'track_index' : track_index,
        'letter' : letter,
    }

    return render_template('spotify/track_cat/track_index.html', **context)


###############
###########################################
#rp routes
@bp.route('/spotify/yesterday')
@bp.route('/spotify/yesterday/')
@cache.cached(timeout=3600)
def yesterday():
    '''
    Route to the recent template.
    '''
    #three_ago = recently_played.query.all()[-3:]
    yesterday_records = recently_played.past_24_hrs_rps()
    song_count_yesterday = len(yesterday_records)
    distinct_arts = len(list(set([i.art_name for i in yesterday_records])))
    known, unknown = recently_played.scan_for_art_cat_awareness(yesterday_records)
    known_cats = list(map(
        artist_catalog.name_to_art_cat,
        known,
    ))
    sorted_known_cats = sorted(known_cats, key=lambda x: (x.master_genre.lower(), x.art_name.lower()))
    context = {
        #'last_three' : three_ago,
        'yesterday_song_count' : song_count_yesterday,
        'distinct_arts' : distinct_arts,
        'known':known,
        'unknown':sorted(unknown, key=lambda x: (x.lower(), x)),
        'known_cats':sorted_known_cats,
    }
    return render_template('spotify/recently_played.html', **context)

@bp.route('/spotify/right_now')
@bp.route('/spotify/right_now/')
#@cache.cached(timeout=3600)
def right_now():
    '''
    Route to the recent template.
    '''
    page = request.args.get('page', 1, type=int)
    per_page = 5
    pagination = recently_played.query.order_by(desc(recently_played.id)).paginate(page=page, per_page=per_page, error_out=False)
    five_ago = pagination.items
    
    cat_scanned = list(map(
        recently_played.cat_scan_rp_object,
        five_ago
    ))

    context = {
        'last_five': cat_scanned,

app/templates/spotify/art_cat/art_cat_base.html
{% include 'base.html' %}

{% set genres = ['electronic', 'pop', 'country', 'funk', 'punk', 'indie', 'rock', 'old', 'other'] %}
{% set alpha = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'] %}
{% set non_alphas = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '@', '#', '$', '%', '&', '*', '!', '?', '+', '-', '['] %}
<head>
<style>
  ul#menu li {
    display:inline;
  }
        /* Genre List Styles */
.genre-list {
  background-color: antiquewhite;
  border-radius: 62%;
  border-bottom: 2px solid brown;
  list-style-type: none; /* Remove bullet points */
  padding: 0; /* Remove default padding */
}

.genre-pill {
  background-color: rgb(38, 80, 21); /* Background color for the pill */
  color: lightgray; /* Text color for the pill */
  border-radius: 20px; /* Adjust the border-radius to control the pill shape */
  display: inline-block; /* Display items horizontally */
  padding: 5px 10px; /* Adjust padding for spacing inside the pill */
  margin: 2px; /* Add margin to separate pills */
  text-decoration: none; /* Remove underline from links */
  font-weight: bold;
}

.genre-pill:hover {
  box-shadow: 0 0 19px rgba(0, 0, 0, 0.5); /* Add drop shadow on hover */
}

/* Alpha List Styles (similar to genre list) */
.alpha-list {
  background-color: antiquewhite;
  border-radius: 62%;
  border-bottom: 2px solid brown;
  list-style-type: none;
  padding: 0;
}

.alpha-pill {
  background-color: rgb(71, 146, 71);
  color: lightgray;
  border-radius: 20px;
  display: inline-block;
  padding: 5px 10px;
  margin: 2px;
  text-decoration: none;
}

.alpha-pill:hover {
  box-shadow: 0 0 19px rgba(0, 0, 0, 0.5); /* Add drop shadow on hover */
}

    </style>
    
    <title>Fred's Record Collection</title>

    </head>

{% include 'spotify/spotify_header.html' %}

<div class="container-fluid text-center">
  <div class="myDiv">
    <!-- Genre List -->
    <ul id="genre_list" class="genre-list">
      {% for genre in genres %}
        <a href="{{ url_for( 'spotify.index_by_genre', master_genre=genre) }}">
          <li class="genre-pill">{{ genre }}</li>
        </a>
      {% endfor %}
    </ul>
    
    <!-- Alpha List -->
    <ul id="alpha_list" class="alpha-list">
      {% for char in alpha %}
        <a href="{{ url_for( 'spotify.index_by_letter', letter=char) }}">
          <li class="alpha-pill">{{ char }}</li>
        </a>
      {% endfor %}
    </ul>

    <form method="POST">
      {{ form.hidden_tag() }}
      {{ form.csrf_token }}
      <p style="color: antiquewhite;">
        {{ form.search_term.label }}
        {{ form.search_term(size=20) }}
      </p>
    </form>
  </div>
</div>
    

{% block content %} {% endblock %}

app/templates/spotify/art_cat/art_cat_genre_index.html
{% for item in art_cat_index %}
        <div class="col-md-3 my-item">

            <div class="card" style="width: 18rem;">
                <img src="https://i.scdn.co/image/{{ item.img_url_mid }}" class="card-img-top my-image" alt="{{ item.art_name }}">
                <div class="card-body">
                    
                    {% if item.master_genre == 'rock' %}
                        <h3 class="my-item-header rock">{{ item.master_genre }}</h3>
                    {% elif item.master_genre == 'pop' %}
                        <h3 class="my-item-header pop">{{ item.master_genre }}</h3>
                    {% elif item.master_genre == 'electronic' %}
                        <h3 class="my-item-header elec">{{ item.master_genre }}</h3>
                    {% elif item.master_genre == 'punk' %}
                        <h3 class="my-item-header punk">{{ item.master_genre }}</h3>
                    {% elif item.master_genre == 'funk' %}
                        <h3 class="my-item-header hop">{{ item.master_genre }}</h3>
                    {% elif item.master_genre == 'indie' %}
                        <h3 class="my-item-header indie">{{ item.master_genre }}</h3>
                    {% elif item.master_genre == 'old' %}
                        <h3 class="my-item-header old">{{ item.master_genre }}</h3>
                    {% elif item.master_genre == 'country' %}
                        <h3 class="my-item-header country">{{ item.master_genre }}</h3>
                    {% else %}
                        <h3 class="my-item-header" style="background-color: w">{{ item.master_genre }}</h3>
                    {% endif %}

                    <p class="card-text">{{ item.genre }}</p>
                    <p class="card-text">{{ item.art_name }}</p>
                    <p class="card-text">{{ item.followers }}</p>
                    <p class="card-text">{{ item.app_record_date }}</p>
                </div>
            </div>

        </div>
{% endfor %}

app/templates/spotify/art_cat/art_cat_index.html
{% extends 'spotify/art_cat/art_cat_base.html' %}

{% block content %}
<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/spotify.css') }}">

<style>
.genre-highlight {
    font-weight: bold;
    color: #00ffbf; /* Change this to the desired color */
}

.sort-link {
    font-style: italic;
    color: #00ffbf; /* Match this color to the genre-highlight color */
    text-decoration: none;
}

.sort-link:hover {
    text-decoration: underline;
}
</style>

<div class="container text-center">
    <div class="row mb-3">
        <div class="col-12">
            <h4><span class="genre-highlight"> {{ artist_count }} </span> artists indexed by <span class="genre-highlight">{{ genre or letter }}</span></h4>
        </div>
    </div>

    {% if sort %}
    <div class="row mb-3">
        <div class="col-12">
            <form method="get" action="{{ url_for('spotify.index_by_genre', master_genre=genre) }}" style="display:inline;">
                <input type="hidden" name="page" value="{{ page }}">
                <input type="hidden" name="sort" value="{{ 'popularity' if sort == 'default' else 'default' }}">
                <button type="submit" class="sort-link btn btn-link">
                    Sort by {{ 'Popularity' if sort == 'default' else 'ABC..' }}
                </button>
            </form>
        </div>
    </div>
    {% endif %}

    {% include 'spotify/art_cat/art_cat_nav_buttons.html' %}

    <div class="row">
        {% for item in art_cat_index %}
            {% include 'spotify/art_cat/art_cat_index_cards.html' %}
        {% endfor %}
    </div>
</div>

{% include 'spotify/art_cat/art_cat_nav_buttons.html' %}

{% endblock %}

app/templates/spotify/art_cat/art_cat_landing.html
{% extends 'spotify/art_cat/art_cat_base.html' %}

{% block content %}


<style>
    body {
    background-color: #0f1f19;
    color: wheat;
  }

    .container {
        max-width: 900px; /* Set the maximum width of the container */
    }

    .card {
        width: 100%;
        height: 100%;
        border: 2px solid;
        transition: background-color 0.3s ease, box-shadow 0.3s ease; /* Add box-shadow to the transition */
    }

    .card:hover {
        box-shadow: inset 0 0 80px rgba(0, 0, 0, 0.5); /* Add inner shadow on hover */
    }

    .card-img-top {
        max-height: 170px; /* Adjust the maximum height of the image */
        object-fit: cover;
    }
</style>

<title>Take A Look Around If You'd Like</title>
<div class="container mt-5 text-center">
    <h3 style="color: wheat;">Fred's Spotify Artists Collection</h3>

    <div class="row">
        
        {% for cell in thruples %}
            <div class="col-md-4 mb-4">
                <div class="card {% if cell.0 in ['rock', 'pop', 'electronic', 'punk', 'funk', 'indie', 'old', 'country'] %}{{ cell.0.lower() }}{% endif %}">
                    <a href="{{ url_for('spotify.index_by_genre', master_genre=cell.0) }}">
                        <img src="https://i.scdn.co/image/{{ cell.2 }}" class="card-img-top" alt="Image">
                    </a>
                    <div class="card-body">
                        <h5 class="white-pill">{{ cell.0 }}</h5>
                        <p class="card-text" style="color: brown;">{{ cell.1 }} artists</p>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
</div>

{% endblock %}

app/templates/spotify/art_cat/art_cat_nav_buttons.html
{% if next_page or prev_page %}
<div class="mt-3 d-flex justify-content-center">
    {% if genre %}
        {% if first_page %}
        <span>
            <a class='first-page btn btn-primary' href="{{ url_for('spotify.index_by_genre', master_genre=genre, page=first_page, sort=sort) }}">
                {{ '<<' }}
            </a>
        </span>
        {% endif %}
        {% if prev_page %}
        <span style="margin-left: 10px;">
            <a class='prev-post btn btn-secondary' href="{{ url_for('spotify.index_by_genre', master_genre=genre, page=prev_page, sort=sort) }}">
                {{ 'Previous' }}
            </a>
        </span>
        {% endif %}
        {% if next_page %}
        <span style="margin-left: 10px;">
            <a class='next-post btn btn-secondary' href="{{ url_for('spotify.index_by_genre', master_genre=genre, page=next_page, sort=sort) }}">
                {{ 'Next' }}
            </a>
        </span>
        {% endif %}
        {% if last_page %}
        <span style="margin-left: 10px;">
            <a class='last-page btn btn-primary' href="{{ url_for('spotify.index_by_genre', master_genre=genre, page=last_page, sort=sort) }}">
                {{ '>>' }}
            </a>
        </span>
        {% endif %}
    {% elif letter %}
        {% if first_page %}
        <span>
            <a class='first-page btn btn-primary' href="{{ url_for('spotify.index_by_letter', letter=letter, page=first_page, sort=sort) }}">
                {{ '<<' }}
            </a>
        </span>
        {% endif %}
        {% if prev_page %}
        <span style="margin-left: 10px;">
            <a class='prev-post btn btn-secondary' href="{{ url_for('spotify.index_by_letter', letter=letter, page=prev_page, sort=sort) }}">
                {{ 'Previous' }}
            </a>
        </span>
        {% endif %}
        {% if next_page %}
        <span style="margin-left: 10px;">
            <a class='next-post btn btn-secondary' href="{{ url_for('spotify.index_by_letter', letter=letter, page=next_page, sort=sort) }}">
                {{ 'Next' }}
            </a>
        </span>
        {% endif %}
        {% if last_page %}
        <span style="margin-left: 10px;">
            <a class='last-page btn btn-primary' href="{{ url_for('spotify.index_by_letter', letter=letter, page=last_page, sort=sort) }}">
                {{ '>>' }}
            </a>
        </span>
        {% endif %}
    {% endif %}
</div>
{% endif %}

app/templates/spotify/art_cat/art_cat_profile.html
{% extends 'spotify/art_cat/art_cat_base.html' %}

{% block content %}

<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/spotify.css') }}">


<section>
    <div class="container py-5">
  
      <div class="row">

        <div class="col-lg-4">
          <div class="card mb-4">
              <div class="card-body text-center">
                <img src="https://i.scdn.co/image/{{ img_url_mid }}" alt="avatar" class="rounded-circle img-fluid with-border" style="width: 150px;">
                  <h5 class="my-3">{{ art_name }}</h5>
                  {% if genre1 %}
                      <p class="white-pill mb-0">
                          <a href="{{ url_for('spotify.index_by_genre', master_genre=genre1) }}">
                              {{ genre1 }}
                          </a>
                      </p>
                  {% endif %}
                  {% if genre2 %}
                      <p class="white-pill mb-0">
                          <a href="{{ url_for('spotify.index_by_genre', master_genre=genre2) }}">
                              {{ genre2 }}
                          </a>
                      </p>
                  {% endif %}
                  {% if genre3 %}
                      <p class="white-pill mb-0">
                          <a href="{{ url_for('spotify.index_by_genre', master_genre=genre3) }}">
                              {{ genre3 }}
                          </a>
                      </p>
                  {% endif %}
                  
                  <hr>
                  <div class="spotify-icon-container" style="margin-bottom: 10px; margin-right: 15px;">
                    <a href="https://open.spotify.com/artist/{{ art_id }}" target="_blank" rel="noopener noreferrer" title="Link to hear on Spotify">
                        <i class="fab fa-spotify fa-3x"></i>
                    </a>
                    
                  </div>
                  <p class="mb-0 ms-2">Spotify Artist URL</p>
                  <div class="spotify-icon-container" style="margin-right: 5px;">
                    <!-- <a href="http://127.0.0.1:5000/spotify/art_cat/artist/dash/{{ art_id }}" target="_blank" rel="noopener noreferrer"> -->
                    <a href="https://fredlambuth.com/spotify/art_cat/artist/dash/{{ art_id }}" target="_blank" rel="noopener noreferrer">
                      <i class="fas fa-chart-line fa-3x"></i>
                    </a>
                    
                  </div>
                  <p class="mb-0 ms-2">Artist Dashboard</p>
              </div>
            </div>

            <div class="card mb-4">
              <div class="card-body">
                  <h5 class="card-title">Peanut Gallery</h5>
                  {% if comments %}
                      {% for comment in comments %}
                          <div class="comment">
                              <div class="row">
                                  <div class="col-4 text-center"> <!-- Increased width to col-4 -->
                                      <img src="{{ url_for('static', filename='img/user_pics/' + comment.user.username + '.jpg') }}" alt="User profile picture" class="rounded-circle img-fluid" style="width: 50px;">
                                      <p class="text-muted">{{ comment.user.username }}</p> <!-- Username text -->
                                  </div>
                                  <div class="col-8">
                                      <div class="comment-content">
                                          <p>{{ comment.content }}</p>
                                          <small class="text-muted">{{ comment.comment_date }}</small>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      {% endfor %}
                  {% else %}
                      <p>No comments available.</p>
                  {% endif %}
              </div>
            </div>
          
            
            <form method="post">
              {{ comment_form.hidden_tag() }}  <!-- Include CSRF token -->
              <div class="form-group">
                  {{ comment_form.content.label(class="form-label") }}
                  {{ comment_form.content(class="form-control") }}
              </div>
              <button type="submit" class="btn btn-primary">Add Comment</button>
            </form>

        </div>

      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">

            <div class="row">
              <div class="col-sm-4">
                <p class="mb-0">Current Spotify Followers</p>
              </div>
              <div class="col-sm-8">
                <p class="mb-0" style="color: wheat;">{{ followers }}</p>
              </div>
              {% if followers_diff and followers_diff_pct is not none %}
              <div class="col-sm-4">
                <p class="mb-0">Change since: {{ prev_date }}</p>
              </div>
              <div class="col-sm-8">
                <p class="mb-0" style="color: {% if followers_diff > 0 %}green{% elif followers_diff < 0 %}red{% else %}wheat{% endif %};">
                  {{ followers_diff }}
                </p>
              </div>              

              <div class="col-sm-4">
                <p class="mb-0">Change Pct:</p>
              </div>
              <div class="col-sm-8">
                <p class="mb-0" style="color: wheat;">{{ followers_diff_pct }}%</p>
              </div>
              {% endif %}
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Total Days on Charts</p>
              </div>
              <div class="col-sm-9">
                <p class="mb-0" style="color: wheat;">{{ total_days_on_charts }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">First Chart Appearance</p>
              </div>
              <div class="col-sm-9">
                <p class="mb-0" style="color: wheat;">{{ first_appearance }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Last Chart Appearance</p>
              </div>
              <div class="col-sm-9">
                <p class="mb-0" style="color: wheat;">{{ last_appearance }}</p>
              </div>
            </div>
          </div>
        </div>

          <div class="row">

            <div class="col-md-6">
                <div class="card mb-4 mb-md-0">
                    <div class="card-body">
                        <p class="mb-4"><span class="text me-1">Listening Streaks</span></p>
            
                        {% if streaks %}
                            <ul class="list-group">
                                {% for date, length in streaks.items() %}
                                    <li class="list-group-item d-flex justify-content-between streak-item" style="color: darkslategray;">
                                        <span>{{ date }}</span>
                                        <span>{{ length }} days</span>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>No listening streaks available.</p>
                        {% endif %}
            
                    </div>
                </div>
            </div>
            

            {% if notable_tracks %}
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4"><span class="text me-1">Favorite Tracks</span> 
                  </p>

                  <ul class="list-group">
                    {% for track in notable_tracks %}
                      <li class="list-group-item d-flex justify-content-between" style="color: darkslategray;">
                        <span><a href="https://open.spotify.com/track/{{ track[1] }}" style="text-decoration: none; color: inherit;">{{ track[0] }}</a></span>
                      </li>
                    {% endfor %}
                </ul>
                  

                </div>
              </div>
            </div>
            {% endif %}

          </div>

        </div>
        
      </div>
    </div>
</section>
{% endblock %}

app/templates/spotify/art_cat/art_cat_search.html
{% include 'spotify/art_cat/art_cat_base.html' %}

{% block content %}
<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/spotify.css') }}">


<div class="container text-center">
    <span class="title"><h1> Spotify Artists Search Results</h1></span>
    <h4>All artists that contain your search terms(s).</h4>
    <hr>
        {% if like_arts %}
        <div class="row">
            {% for item in like_arts %}
    
            {% include 'spotify/art_cat/art_cat_index_cards.html' %}
            
            {% endfor %}
        </div>
        {% else%}
        <p>No Artist Matches</p>
        {% endif %}

</div>

{% endblock %}